server:
  port: 8763
spring:
  application:
    name: service-hi
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    password:
#    database: 0 # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
#    timeout: 60000 # 连接超时时间（毫秒）
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）默认 8
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）默认 -1
#        max-idle: 8 # 连接池中的最大空闲连接默认 8
#        min-idle: 0 # 连接池中的最小空闲连接默认 0
#  data:
#    mongodb:
#      uri: mongodb://127.0.0.1:27017/test # mongodb连接
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

